
name: Unzip to Root

on:
  push:
    paths:
      - "**/*.zip"

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Unzip files
      run: |
        find . -type f -name "*.zip" | while read file; do
          # فك الضغط في المسار الرئيسي
          unzip -o "$file" -d "."
          rm "$file"
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Unzipped files to root" && git push)
