name: Unzip Uploaded Files

on:
  push:
    paths:
      - "**/*.zip"

# إضافة الصلاحيات عشان يقدر يعمل Push
permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # تحديث للإصدار الأحدث

    - name: Unzip files
      run: |

        find . -type f -name "*.zip" | while read file; do
          folder="${file%.zip}"
          mkdir -p "$folder"
          unzip -o "$file" -d "$folder"
          rm "$file"
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        # التريكه دي عشان لو مفيش تغييرات السكريبت ميفشلش
        git diff --quiet && git diff --staged --quiet || (git commit -m "Unzipped newly uploaded files" && git push)
